# Generated by Django 3.1 on 2020-10-15 01:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('relevanceScore', models.FloatField(blank=True, default=0, null=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('keyword', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('description', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('url', models.CharField(max_length=200)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineArticle',
            fields=[
                ('description', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('url', models.CharField(max_length=200)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('description', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=30)),
                ('format', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('url', models.CharField(max_length=200)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('description', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=30)),
                ('format', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('url', models.CharField(max_length=200)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='contentRelated', to='content.Interest'),
        ),
    ]
