# Generated by Django 3.1.4 on 2020-12-17 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201014_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
